services:
  - type: web
    name: statcan-explorer
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python proxy.py
    envVars:
      - key: PORT
        value: 10000

  - type: web
    name: statcan-explorer-ev
    runtime: node
    rootDir: ev-dashboard
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
