#!/usr/bin/env python3
"""Generate the launchd plist that triggers refresh.py on StatCan release dates.

Reads release_dates.txt (the CIMT release calendar) and writes
com.statcan.cimt-refresh.plist with one StartCalendarInterval entry per date, at
RELEASE_TIME local time. StatCan publishes at 08:30 ET; we fire a few minutes
later so the bulk file is posted, and refresh.py (--retry) re-checks for a while
in case it lands late.

NOTE: launchd uses the Mac's LOCAL time. These dates/times assume the machine is
on Eastern time (matching the 08:30 ET release). Adjust RELEASE_TIME if not.

Run this whenever you update release_dates.txt:
    python make_refresh_plist.py
Then reload the agent (see README).
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
DATES = HERE / "release_dates.txt"
PLIST = HERE / "com.statcan.cimt-refresh.plist"

# Where the job runs from on the user's machine (TCC-safe home clone).
SCRIPT = "/Users/jasonkirby/statcan-explorer/cimt/refresh.py"
LOG = "/Users/jasonkirby/statcan-explorer/cimt/cimt_refresh.log"
# Use the interpreter that has duckdb/pyarrow/requests/boto3 installed (the
# framework python), not /usr/bin/python3 which lacks them.
PYTHON = sys.executable
RELEASE_HOUR, RELEASE_MIN = 8, 35       # ~5 min after the 08:30 ET release


def read_dates() -> list[tuple[int, int, int]]:
    out = []
    for line in DATES.read_text().splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        y, m, d = (int(x) for x in line.split("-"))
        out.append((y, m, d))
    return sorted(set(out))


def build(dates) -> str:
    entries = []
    for (_y, m, d) in dates:
        entries.append(
            "    <dict>\n"
            f"      <key>Month</key><integer>{m}</integer>\n"
            f"      <key>Day</key><integer>{d}</integer>\n"
            f"      <key>Hour</key><integer>{RELEASE_HOUR}</integer>\n"
            f"      <key>Minute</key><integer>{RELEASE_MIN}</integer>\n"
            "    </dict>")
    # launchd has no year field, so we list Month+Day. The dates here run
    # through Feb 2027 and don't repeat within that window; regenerate before
    # they wrap around a year later.
    span = f"{dates[0][0]}-{dates[0][1]:02d} .. {dates[-1][0]}-{dates[-1][1]:02d}"
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<!-- GENERATED by make_refresh_plist.py from release_dates.txt. Do not hand-edit.
     CIMT merchandise-trade release days {span}, {RELEASE_HOUR:02d}:{RELEASE_MIN:02d} local (ET). -->
<dict>
  <key>Label</key>
  <string>com.statcan.cimt-refresh</string>

  <key>ProgramArguments</key>
  <array>
    <string>{PYTHON}</string>
    <string>{SCRIPT}</string>
    <string>--retry</string>
  </array>

  <key>StartCalendarInterval</key>
  <array>
{chr(10).join(entries)}
  </array>

  <key>StandardOutPath</key>
  <string>{LOG}</string>
  <key>StandardErrorPath</key>
  <string>{LOG}</string>

  <key>RunAtLoad</key>
  <false/>
</dict>
</plist>
"""


def main() -> int:
    dates = read_dates()
    if not dates:
        print(f"no dates in {DATES}")
        return 1
    PLIST.write_text(build(dates))
    print(f"wrote {PLIST.name} with {len(dates)} release triggers "
          f"at {RELEASE_HOUR:02d}:{RELEASE_MIN:02d} local:")
    for (y, m, d) in dates:
        print(f"  {y}-{m:02d}-{d:02d}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
